// Module - Encapsulated Code (only share minimum)
const names = require('./4-names.js')
const sayHi = require('./5-utils.js')
console.log(names)
const data = require('./6-alternative-flavor.js')
//sayHi("Long")
//sayHi(names.john)
//sayHi(names.peter)

require('./7-mind-grenade.js')